### health
GET http://localhost:8002/health

### discovered services from facade (Kubernetes endpoints)
GET http://localhost:8002/services

### msg1
POST http://localhost:8002/transaction
Content-Type: application/json

{
  "user_id": "msg1",
  "amount": 1.0
}

### msg2
POST http://localhost:8002/transaction
Content-Type: application/json

{
  "user_id": "msg2",
  "amount": 2.0
}

### msg3
POST http://localhost:8002/transaction
Content-Type: application/json

{
  "user_id": "msg3",
  "amount": 3.0
}

### msg4
POST http://localhost:8002/transaction
Content-Type: application/json

{
  "user_id": "msg4",
  "amount": 4.0
}

### msg5
POST http://localhost:8002/transaction
Content-Type: application/json

{
  "user_id": "msg5",
  "amount": 5.0
}

### get one user
GET http://localhost:8002/user/msg1

### get all balances
GET http://localhost:8002/accounts

### metrics
GET http://localhost:8002/metrics

### reset metrics
POST http://localhost:8002/metrics/reset
