apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservices-sa
  namespace: micro-lab5
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: microservices-reader
  namespace: micro-lab5
rules:
  - apiGroups: [""]
    resources: ["configmaps", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: microservices-reader-binding
  namespace: micro-lab5
subjects:
  - kind: ServiceAccount
    name: microservices-sa
    namespace: micro-lab5
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: microservices-reader
