apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-service
  namespace: micro-lab5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: logging-service
  template:
    metadata:
      labels:
        app: logging-service
    spec:
      serviceAccountName: microservices-sa
      containers:
        - name: logging-service
          image: software-architecture-labs/logging-service:lab5
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
            - name: grpc
              containerPort: 50051
          env:
            - name: SERVICE_NAME
              value: logging-service
            - name: APP_CONFIGMAP_NAME
              value: microservices-config
            - name: LOGGING_GRPC_PORT
              value: "50051"
            - name: LOGGING_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: logging-service
  namespace: micro-lab5
spec:
  selector:
    app: logging-service
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: grpc
    - name: http
      protocol: TCP
      port: 8000
      targetPort: http
